FROM cimg/node:%%TAG%%@%%SHA%%

# home folder
ENV HOME /home/circleci

# good colors for most applications
ENV TERM xterm

# no interactive frontend during docker build
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# set npm path for global modules
ENV NPM_CONFIG_PREFIX $HOME/.npm-global
# add npm global packages to path
ENV PATH $PATH:$HOME/.npm-global/bin

# set yarn path for global modules
RUN yarn config set prefix $HOME/.yarn
# add yarn global packages to path
ENV PATH $PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin

# create local bin dir
RUN mkdir -p $HOME/bin
# add local bin dir to path
ENV PATH $PATH:$HOME/bin

# avoid million NPM install messages
ENV npm_config_loglevel warn

# install latest npm, regardless of node version, for speed and fixes
RUN npm install -g npm@%%NPM_VERSION%%

# verify npm works
RUN npm doctor

WORKDIR $HOME/project
