name: Docker Image (library/node) CI

on:
  push:
    branches: [ master ]
    paths:
      - '**'
      - versions.json
      - docker-entrypoint.sh
      - '.github/workflows/build-library-node.yml'

jobs:
  build_and_push:
    strategy:
      matrix:
        node: [ '12.22', '12.22-npm6', '14.16', '14.16-npm6', '15.11']
        distro: [ focal, alpine ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee5a9d1395988d7c82c67c69571871f5994b94df # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@6520a2d2cb6db42c90c297c8025839c98e531268 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@3b70782066bd817837b6bd8c518d45b54d91bf76 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-${{
            github.sha }}
          restore-keys: |
            node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push (${{ matrix.distro }}[${{ matrix.node }}])
        uses: docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f # pin@v2
        with:
          context: .
          file: ./${{ matrix.distro }}/${{ matrix.node }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/${{ matrix.distro }}:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}-${{ matrix.distro }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
