name: Docker Image (library/node) CI

on:
  push:
    branches: [master]
    paths:
      - "output/**"
      - docker-entrypoint.sh
      - ".github/workflows/build-library-node.yml"

jobs:
  build_and_push:
    strategy:
      matrix:
        node: ["16.20", "18.16", "20.0"]
        distro: [alpine, debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-${{ github.sha }}
          restore-keys: |
            node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push (${{ matrix.distro }}[${{ matrix.node }}])
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v2
        with:
          context: .
          file: ./output/${{ matrix.distro }}/${{ matrix.node }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/${{ matrix.distro }}:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}-${{ matrix.distro }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
