name: Docker Image (library/node) CI

on:
  push:
    branches: [ dev ]
    paths:
      - '**'
      - versions.json
      - docker-entrypoint.sh
      - '.github/workflows/build-library-node.yml'

jobs:
  build_and_push:
    strategy:
      matrix:
        node: [ '14.17']
        distro: [ dev ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee5a9d1395988d7c82c67c69571871f5994b94df # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@3b70782066bd817837b6bd8c518d45b54d91bf76 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-${{
            github.sha }}
          restore-keys: |
            node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push (${{ matrix.distro }}[${{ matrix.node }}])
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc # pin@v2
        with:
          context: .
          file: ./${{ matrix.distro }}/${{ matrix.node }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/${{ matrix.distro }}:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}-${{ matrix.distro }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
