name: Docker Image (library/node) CI

on:
  push:
    branches: [master]
    paths:
      - "output/**"
      - docker-entrypoint.sh
      - ".github/workflows/build-library-node.yml"

jobs:
  build_and_push:
    strategy:
      matrix:
        node: ["14.21", "16.19", "18.12"]
        distro: [alpine, debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98 # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-${{ github.sha }}
          restore-keys: |
            node-${{ runner.os }}-${{ matrix.node }}-${{ matrix.distro }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push (${{ matrix.distro }}[${{ matrix.node }}])
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 # pin@v2
        with:
          context: .
          file: ./output/${{ matrix.distro }}/${{ matrix.node }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/${{ matrix.distro }}:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}-${{ matrix.distro }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
